language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "firekicks-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: fire-kicks
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: tYRwnvadoTfn28kLCA5PG5AcGG3tbwtPUz7KkZ7HwAesU30z1C3t39CGhYlnMu8YPd8zve6q+4n8Ns7tS28AoItfe4ww2Ssl39weVHm23XDipDnAedl6XMP/LWMlYEgwlnZokFowyTfpxyTN0tsimpNGX7N1hdvPbkDQYpzEsqYEEhstRTLeF7DD6ps8GijVjtkhmlmj+i1hjlNKOVLnS37GBWMbumykCP/dxVjS4yvXCm9tgSLB5f6eGJpMiyf5mpRe5cjiyPRBIN+5+by9le9KcTMmA2QwAtJZDKIg8ASQeYhDdZ3T9e9iGUIQREUEdFgJALkhbPoPvAqVAKrb1d04vEZ1mE6IpbXHDJl7tcmxEVY85OqBd3aifztTpVgzfQeGYapzPK6b6GkpY44RihC3kdHCV7Ut6p3Hx6nwwpxnOBmzesbDDoUJT/mo/vgBkFkfDgWEYXyHtn+ibBAXdk9wgWerFvighDMYYqiFnj9bbBhFMIRLtD3oHvWv4x9OC2mShGSeiHsZao5J1iW6cUy3msIBQh2J6iRIXuFEgYVgmvKtga8g6OG9TyHkhs1QjUYZRTTiCT6+tWa0To+Xu9WkG4ADIPlquzT/kFyJMNcJlvZw41d+5IHPOP7vzX45AOcNo05AZLlgI+ZZonM2LaValgimr6jPGAMGhFsOsrc=
